import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import AppProvider from "@/context/appContext";

export const metadata: Metadata = {
  title: "Dreic Leal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[100%]">
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
